export const PERMISSIONS = {
  'business:read': 'business:read',
  'business:write': 'business:write',
  'team:read': 'team:read',
  'team:write': 'team:write',
  'customers:read': 'customers:read',
  'customers:write': 'customers:write',
  'conversations:read': 'conversations:read',
  'conversations:write': 'conversations:write',
  'appointments:read': 'appointments:read',
  'appointments:write': 'appointments:write',
  'knowledge:read': 'knowledge:read',
  'knowledge:write': 'knowledge:write',
  'analytics:read': 'analytics:read',
  'billing:read': 'billing:read',
  'billing:write': 'billing:write',
  'settings:read': 'settings:read',
  'settings:write': 'settings:write',
  'ai:configure': 'ai:configure',
  'audit:read': 'audit:read',
  'campaigns:read': 'campaigns:read',
  'campaigns:write': 'campaigns:write',
  'employees:read': 'employees:read',
  'employees:write': 'employees:write',
  'employee-comms:read': 'employee-comms:read',
  'employee-comms:write': 'employee-comms:write',
  'platform:admin': 'platform:admin',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type Role = 'OWNER' | 'ADMIN' | 'MANAGER' | 'AGENT' | 'VIEWER' | 'RECEPTIONIST' | 'STAFF';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: Object.values(PERMISSIONS).filter((p) => p !== PERMISSIONS['platform:admin']),
  ADMIN: Object.values(PERMISSIONS).filter(
    (p) => !p.startsWith('billing:write') && p !== PERMISSIONS['platform:admin']
  ),
  MANAGER: [
    PERMISSIONS['business:read'],
    PERMISSIONS['team:read'],
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['knowledge:write'],
    PERMISSIONS['analytics:read'],
    PERMISSIONS['settings:read'],
    PERMISSIONS['audit:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['campaigns:write'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employees:write'],
    PERMISSIONS['employee-comms:read'],
    PERMISSIONS['employee-comms:write'],
  ],
  AGENT: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employee-comms:read'],
  ],
  RECEPTIONIST: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['analytics:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['campaigns:write'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employee-comms:read'],
  ],
  STAFF: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['knowledge:read'],
  ],
  VIEWER: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['analytics:read'],
  ],
};

export const ROUTE_PERMISSIONS: Record<string, Permission> = {
  '/dashboard': PERMISSIONS['analytics:read'],
  '/conversations': PERMISSIONS['conversations:read'],
  '/customers': PERMISSIONS['customers:read'],
  '/appointments': PERMISSIONS['appointments:read'],
  '/ai-training': PERMISSIONS['knowledge:read'],
  '/knowledge': PERMISSIONS['knowledge:read'],
  '/analytics': PERMISSIONS['analytics:read'],
  '/ai-analytics': PERMISSIONS['analytics:read'],
  '/team': PERMISSIONS['team:read'],
  '/settings': PERMISSIONS['settings:read'],
  '/billing': PERMISSIONS['billing:read'],
  '/notifications': PERMISSIONS['conversations:read'],
  '/audit-logs': PERMISSIONS['audit:read'],
  '/campaigns': PERMISSIONS['campaigns:read'],
  '/employee-comms': PERMISSIONS['employee-comms:read'],
  '/super-admin': PERMISSIONS['platform:admin'],
  '/admin/businesses': PERMISSIONS['platform:admin'],
  '/admin/users': PERMISSIONS['platform:admin'],
};
