import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, FlaskConical, GitBranch, Radio } from 'lucide-react';
import { toast } from 'sonner';
import api, { extractData, getErrorMessage } from '@/lib/api';
import type { AgentChannelBinding, AgentIncident, AgentSimulationRun, AgentWorkflow } from '@/lib/agent-studio';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { LoadingState } from '@/components/LoadingState';

export function AgentAdvancedOpsPanel({ agentId, canEdit }: { agentId: string; canEdit: boolean }) {
  const client = useQueryClient();
  const workflows = useQuery({ queryKey: ['agent-ops', agentId, 'workflows'], queryFn: async () => extractData<AgentWorkflow[]>(await api.get(`/ai-agent-studio/${agentId}/workflows`)) });
  const simulations = useQuery({ queryKey: ['agent-ops', agentId, 'simulations'], queryFn: async () => extractData<AgentSimulationRun[]>(await api.get(`/ai-agent-studio/${agentId}/simulations`)) });
  const incidents = useQuery({ queryKey: ['agent-ops', agentId, 'incidents'], queryFn: async () => extractData<AgentIncident[]>(await api.get(`/ai-agent-studio/${agentId}/incidents`)) });
  const channels = useQuery({ queryKey: ['agent-ops', agentId, 'channels'], queryFn: async () => extractData<AgentChannelBinding[]>(await api.get(`/ai-agent-studio/${agentId}/channels`)) });
  const refresh = () => client.invalidateQueries({ queryKey: ['agent-ops', agentId] });
  const starterWorkflow = useMutation({ mutationFn: () => api.post(`/ai-agent-studio/${agentId}/workflows`, { name: `WhatsApp reception ${Date.now()}`, description: 'Safe reception flow with human handover', triggerType: 'MESSAGE_RECEIVED', publish: false, nodes: [{ id: 'inbound', type: 'TRIGGER', config: {} }, { id: 'answer', type: 'AI_RESPONSE', config: { groundedOnly: true } }, { id: 'handover', type: 'HANDOVER', config: { onLowConfidence: true } }, { id: 'done', type: 'END', config: {} }], edges: [{ id: 'e1', source: 'inbound', target: 'answer' }, { id: 'e2', source: 'answer', target: 'handover' }, { id: 'e3', source: 'handover', target: 'done' }] }), onSuccess: async () => { await refresh(); toast.success('Validated workflow draft created'); }, onError: (error) => toast.error(getErrorMessage(error)) });
  const redTeam = useMutation({ mutationFn: () => api.post(`/ai-agent-studio/${agentId}/simulations`, { suiteType: 'RED_TEAM', scenarios: [] }), onSuccess: async () => { await refresh(); toast.success('Red-team suite completed'); }, onError: (error) => toast.error(getErrorMessage(error)) });
  const scan = useMutation({ mutationFn: () => api.post(`/ai-agent-studio/${agentId}/incidents/scan`), onSuccess: async () => { await refresh(); toast.success('Operational health scan completed'); }, onError: (error) => toast.error(getErrorMessage(error)) });
  if (workflows.isPending || simulations.isPending || incidents.isPending || channels.isPending) return <LoadingState rows={6} />;
  return <div className="grid gap-5 lg:grid-cols-2">
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitBranch className="h-5 w-5" /> Visual workflows</CardTitle><CardDescription>Validated node-and-edge automation definitions; activation is revision-safe.</CardDescription></CardHeader><CardContent className="space-y-3">{workflows.data?.map((flow) => <div key={flow.id} className="rounded-lg border p-3"><div className="flex justify-between"><div><strong>{flow.name}</strong><p className="text-xs text-muted-foreground">{flow.nodes.length} nodes · revision {flow.revision}</p></div><Badge variant="outline">{flow.status}</Badge></div><div className="mt-3 flex flex-wrap items-center gap-2">{flow.nodes.map((node, index) => <div key={node.id} className="flex items-center gap-2"><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-medium">{node.type.replace('_', ' ')}</span>{index < flow.nodes.length - 1 && <span className="text-muted-foreground">→</span>}</div>)}</div></div>)}{!workflows.data?.length && <p className="text-sm text-muted-foreground">No workflows configured.</p>}{canEdit && <Button onClick={() => starterWorkflow.mutate()}>Create safe starter workflow</Button>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><FlaskConical className="h-5 w-5" /> Simulation & red-team</CardTitle><CardDescription>Regression and adversarial safety evidence before production.</CardDescription></CardHeader><CardContent className="space-y-3">{simulations.data?.slice(0, 5).map((run) => <div key={run.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{run.suiteType}</span><strong>{run.score ?? 0}% · {run.status}</strong></div>)}{canEdit && <Button variant="outline" onClick={() => redTeam.mutate()}>Run built-in red-team suite</Button>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5" /> WhatsApp SRE incidents</CardTitle><CardDescription>Threshold breaches automatically engage the rollout kill switch.</CardDescription></CardHeader><CardContent className="space-y-3">{incidents.data?.filter((item) => item.status !== 'RESOLVED').map((item) => <div key={item.id} className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm"><strong>{item.severity}: {item.type}</strong><p>{item.summary}</p></div>)}{canEdit && <Button variant="outline" onClick={() => scan.mutate()}>Run health scan</Button>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Radio className="h-5 w-5" /> Channel foundation</CardTitle><CardDescription>WhatsApp is live; future connectors remain configuration-only until separately released.</CardDescription></CardHeader><CardContent className="space-y-3">{channels.data?.map((binding) => <div key={binding.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{binding.channel}</span><Badge variant={binding.status === 'ACTIVE' ? 'default' : 'outline'}>{binding.status}</Badge></div>)}<div className="flex flex-wrap gap-2">{['INSTAGRAM','MESSENGER','TIKTOK','WEBCHAT'].map((channel) => <Badge key={channel} variant="outline">{channel} · ready</Badge>)}</div></CardContent></Card>
  </div>;
}
