import type { PlatformFeatureReleaseType, PlatformFeatureStatus } from '@prisma/client';

export interface FeatureRegistryEntry {
  featureKey: string;
  name: string;
  description: string;
  category: string;
  version?: string;
  module: string;
  status?: PlatformFeatureStatus;
  releaseType?: PlatformFeatureReleaseType;
  routePath?: string;
  apiPrefix?: string;
  navLabel?: string;
  isNavItem?: boolean;
  blocksAi?: boolean;
  blocksJobs?: boolean;
  dependsOn?: string[];
}

export const FEATURE_CATEGORIES = [
  'AI Features',
  'CRM Features',
  'Appointments',
  'Analytics',
  'Billing',
  'Campaigns',
  'Automation',
  'WhatsApp',
  'Knowledge Base',
  'Security',
  'Experimental',
  'Beta Features',
  'Premium Features',
  'Internal Features',
  'Future Features',
] as const;

export const PLATFORM_FEATURE_REGISTRY: FeatureRegistryEntry[] = [
  // Core platform
  {
    featureKey: 'dashboard',
    name: 'Dashboard',
    description: 'Business overview dashboard with KPIs and activity summaries.',
    category: 'Analytics',
    module: 'dashboard',
    status: 'ENABLED',
    routePath: '/dashboard',
    navLabel: 'Dashboard',
    isNavItem: true,
  },
  {
    featureKey: 'conversations',
    name: 'Conversations',
    description: 'WhatsApp and omnichannel conversation inbox.',
    category: 'WhatsApp',
    module: 'conversations',
    status: 'ENABLED',
    routePath: '/conversations',
    navLabel: 'Conversations',
    isNavItem: true,
    blocksAi: true,
    blocksJobs: true,
  },
  {
    featureKey: 'customers',
    name: 'Customers',
    description: 'CRM customer profiles, segments, and contact management.',
    category: 'CRM Features',
    module: 'customers',
    status: 'ENABLED',
    routePath: '/customers',
    navLabel: 'Customers',
    isNavItem: true,
  },
  {
    featureKey: 'customer-import',
    name: 'Customer Import',
    description: 'Bulk customer CSV import and validation.',
    category: 'CRM Features',
    module: 'customer-import',
    status: 'ENABLED',
    routePath: '/customers/import',
    apiPrefix: '/customer-import',
    navLabel: 'Customer Import',
    isNavItem: true,
  },
  {
    featureKey: 'appointments',
    name: 'Appointments',
    description: 'Appointment scheduling, calendar, and booking management.',
    category: 'Appointments',
    module: 'appointments',
    status: 'ENABLED',
    routePath: '/appointments',
    apiPrefix: '/appointments',
    navLabel: 'Appointments',
    isNavItem: true,
    blocksJobs: true,
  },
  {
    featureKey: 'appointment-automation',
    name: 'Appointment Workflow Builder',
    description: 'Enterprise appointment automation workflows, reminders, and timeline.',
    category: 'Automation',
    module: 'appointment-automation',
    status: 'DISABLED',
    releaseType: 'BETA',
    routePath: '/appointments/automation',
    apiPrefix: '/appointment-automation',
    navLabel: 'Workflow Builder',
    isNavItem: true,
    blocksAi: true,
    blocksJobs: true,
    dependsOn: ['appointments'],
  },
  {
    featureKey: 'campaigns',
    name: 'Campaign Center',
    description: 'Marketing campaigns, journeys, and broadcast automation.',
    category: 'Campaigns',
    module: 'campaigns',
    status: 'ENABLED',
    routePath: '/campaigns',
    apiPrefix: '/campaigns',
    navLabel: 'Campaign Center',
    isNavItem: true,
    blocksJobs: true,
  },
  {
    featureKey: 'employee-comms',
    name: 'Employee Communications',
    description: 'Internal employee broadcast and messaging center.',
    category: 'Campaigns',
    module: 'employee-comms',
    status: 'ENABLED',
    routePath: '/employee-comms',
    apiPrefix: '/employee-comms',
    navLabel: 'Employee Comms',
    isNavItem: true,
    blocksJobs: true,
  },
  {
    featureKey: 'ai-training',
    name: 'AI Training',
    description: 'Knowledge base management and AI training workspace.',
    category: 'Knowledge Base',
    module: 'knowledge',
    status: 'ENABLED',
    routePath: '/ai-training',
    apiPrefix: '/knowledge',
    navLabel: 'AI Training',
    isNavItem: true,
    blocksAi: true,
    blocksJobs: true,
  },
  {
    featureKey: 'ai-analytics',
    name: 'AI Analytics',
    description: 'AI token usage, cost intelligence, and conversation analytics.',
    category: 'AI Features',
    module: 'ai-analytics',
    status: 'ENABLED',
    routePath: '/ai-analytics',
    apiPrefix: '/ai-analytics',
    navLabel: 'AI Analytics',
    isNavItem: true,
    dependsOn: ['ai-training'],
  },
  {
    featureKey: 'analytics',
    name: 'Analytics',
    description: 'Business performance analytics and reporting.',
    category: 'Analytics',
    module: 'analytics',
    status: 'ENABLED',
    routePath: '/analytics',
    apiPrefix: '/analytics',
    navLabel: 'Analytics',
    isNavItem: true,
  },
  {
    featureKey: 'team',
    name: 'Team Management',
    description: 'Team members, roles, and invitations.',
    category: 'Security',
    module: 'team',
    status: 'ENABLED',
    routePath: '/team',
    apiPrefix: '/team',
    navLabel: 'Team',
    isNavItem: true,
  },
  {
    featureKey: 'notifications',
    name: 'Notifications',
    description: 'In-app notification center.',
    category: 'Internal Features',
    module: 'notifications',
    status: 'ENABLED',
    routePath: '/notifications',
    apiPrefix: '/notifications',
    navLabel: 'Notifications',
    isNavItem: true,
  },
  {
    featureKey: 'audit-logs',
    name: 'Audit Logs',
    description: 'Business audit trail and compliance logs.',
    category: 'Security',
    module: 'audit',
    status: 'ENABLED',
    routePath: '/audit-logs',
    apiPrefix: '/audit',
    navLabel: 'Audit Logs',
    isNavItem: true,
  },
  {
    featureKey: 'settings',
    name: 'Settings',
    description: 'Business settings and configuration.',
    category: 'Internal Features',
    module: 'settings',
    status: 'ENABLED',
    routePath: '/settings',
    apiPrefix: '/business',
    navLabel: 'Settings',
    isNavItem: true,
  },
  {
    featureKey: 'billing',
    name: 'Billing',
    description: 'Subscription billing and usage.',
    category: 'Billing',
    module: 'billing',
    status: 'ENABLED',
    routePath: '/billing',
    apiPrefix: '/billing',
    navLabel: 'Billing',
    isNavItem: true,
  },
  {
    featureKey: 'whatsapp',
    name: 'WhatsApp Integration',
    description: 'WhatsApp Business API connection and messaging.',
    category: 'WhatsApp',
    module: 'whatsapp',
    status: 'ENABLED',
    apiPrefix: '/whatsapp',
    blocksJobs: true,
  },
  {
    featureKey: 'ai-chat',
    name: 'AI Chat Engine',
    description: 'Automated AI replies for WhatsApp conversations.',
    category: 'AI Features',
    module: 'ai',
    status: 'ENABLED',
    apiPrefix: '/ai',
    blocksAi: true,
    blocksJobs: true,
    dependsOn: ['ai-training', 'whatsapp'],
  },
  {
    featureKey: 'rag-engine',
    name: 'RAG Knowledge Engine',
    description: 'Retrieval-augmented generation and embeddings pipeline.',
    category: 'AI Features',
    module: 'rag',
    status: 'ENABLED',
    blocksAi: true,
    dependsOn: ['ai-training'],
  },
  {
    featureKey: 'governance',
    name: 'Governance',
    description: 'Enterprise governance approval workflows.',
    category: 'Security',
    module: 'governance',
    status: 'ENABLED',
    apiPrefix: '/governance',
  },
  // Super Admin modules
  {
    featureKey: 'super-admin',
    name: 'Super Admin Console',
    description: 'Platform-wide super admin dashboard.',
    category: 'Internal Features',
    module: 'super-admin',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/super-admin',
    apiPrefix: '/super-admin',
    navLabel: 'Super Admin',
    isNavItem: true,
  },
  {
    featureKey: 'ai-training-center',
    name: 'AI Training Center',
    description: 'Super admin AI training operations center.',
    category: 'AI Features',
    module: 'ai-training-mgmt',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/ai-training',
    apiPrefix: '/super-admin/ai-training-center',
    navLabel: 'AI Training Center',
    isNavItem: true,
    dependsOn: ['ai-training'],
  },
  {
    featureKey: 'ai-analytics-admin',
    name: 'AI Analytics Admin',
    description: 'Platform-wide AI analytics administration.',
    category: 'AI Features',
    module: 'ai-analytics',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/ai-analytics',
    apiPrefix: '/super-admin/ai-analytics',
    navLabel: 'AI Analytics',
    isNavItem: true,
    dependsOn: ['ai-analytics'],
  },
  {
    featureKey: 'business-management',
    name: 'Business Management',
    description: 'Super admin business and user management.',
    category: 'Internal Features',
    module: 'super-admin',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/businesses',
    navLabel: 'Business Management',
    isNavItem: true,
  },
  {
    featureKey: 'subscription-management',
    name: 'Subscription Management',
    description: 'Enterprise subscription license administration.',
    category: 'Billing',
    module: 'subscription',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/subscriptions',
    apiPrefix: '/super-admin/subscriptions',
    navLabel: 'Subscriptions',
    isNavItem: true,
  },
  {
    featureKey: 'financial-intelligence',
    name: 'Financial Intelligence',
    description: 'Enterprise financial intelligence, revenue, cost, and profit analytics.',
    category: 'Billing',
    module: 'financial-intelligence',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/financial-intelligence',
    apiPrefix: '/super-admin/financial-intelligence',
    navLabel: 'Financial Intelligence',
    isNavItem: true,
    dependsOn: ['subscription-management'],
  },
  {
    featureKey: 'governance-admin',
    name: 'Governance Admin',
    description: 'Super admin governance request management.',
    category: 'Security',
    module: 'governance',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/governance',
    navLabel: 'Governance',
    isNavItem: true,
    dependsOn: ['governance'],
  },
  {
    featureKey: 'feature-management',
    name: 'Feature Management Center',
    description: 'Enterprise feature flag registry and activation control.',
    category: 'Internal Features',
    module: 'feature-management',
    status: 'ENABLED',
    releaseType: 'INTERNAL',
    routePath: '/admin/feature-management',
    apiPrefix: '/super-admin/feature-management',
    navLabel: 'Feature Management',
    isNavItem: true,
  },
  // Future Features marketplace
  {
    featureKey: 'ai-voice-assistant',
    name: 'AI Voice Assistant',
    description: 'Voice-based AI receptionist for phone calls.',
    category: 'Future Features',
    module: 'ai-voice',
    status: 'DISABLED',
    releaseType: 'FUTURE',
    blocksAi: true,
    dependsOn: ['ai-chat'],
  },
  {
    featureKey: 'business-scoped-features',
    name: 'Business-Scoped Feature Flags',
    description: 'Per-business feature activation (multi-tenant rollout).',
    category: 'Future Features',
    module: 'feature-management',
    status: 'DISABLED',
    releaseType: 'FUTURE',
  },
  {
    featureKey: 'feature-marketplace',
    name: 'Feature Marketplace',
    description: 'Self-service feature discovery and request portal.',
    category: 'Future Features',
    module: 'feature-management',
    status: 'DISABLED',
    releaseType: 'FUTURE',
  },
  {
    featureKey: 'ai-automation-studio',
    name: 'AI Automation Studio',
    description: 'Visual AI workflow builder for cross-module automation.',
    category: 'Future Features',
    module: 'automation',
    status: 'DISABLED',
    releaseType: 'FUTURE',
    blocksAi: true,
    dependsOn: ['appointment-automation', 'ai-chat'],
  },
  {
    featureKey: 'premium-white-label',
    name: 'White Label Branding',
    description: 'Custom branding and domain for enterprise tenants.',
    category: 'Premium Features',
    module: 'billing',
    status: 'DISABLED',
    releaseType: 'PREMIUM',
  },
  {
    featureKey: 'experimental-multi-agent',
    name: 'Multi-Agent AI Orchestration',
    description: 'Experimental multi-agent AI coordination layer.',
    category: 'Experimental',
    module: 'ai',
    status: 'DISABLED',
    releaseType: 'EXPERIMENTAL',
    blocksAi: true,
    dependsOn: ['ai-chat', 'rag-engine'],
  },
];
