export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  AGENT: 'AGENT',
  VIEWER: 'VIEWER',
  RECEPTIONIST: 'RECEPTIONIST',
  STAFF: 'STAFF',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  'business:read': 'business:read',
  'business:write': 'business:write',
  'team:read': 'team:read',
  'team:write': 'team:write',
  'customers:read': 'customers:read',
  'customers:write': 'customers:write',
  'conversations:read': 'conversations:read',
  'conversations:write': 'conversations:write',
  'appointments:read': 'appointments:read',
  'appointments:write': 'appointments:write',
  'knowledge:read': 'knowledge:read',
  'knowledge:write': 'knowledge:write',
  'analytics:read': 'analytics:read',
  'billing:read': 'billing:read',
  'billing:write': 'billing:write',
  'settings:read': 'settings:read',
  'settings:write': 'settings:write',
  'ai:configure': 'ai:configure',
  'audit:read': 'audit:read',
  'campaigns:read': 'campaigns:read',
  'campaigns:write': 'campaigns:write',
  'employees:read': 'employees:read',
  'employees:write': 'employees:write',
  'employee-comms:read': 'employee-comms:read',
  'employee-comms:write': 'employee-comms:write',
  'platform:admin': 'platform:admin',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: Object.values(PERMISSIONS).filter((p) => p !== PERMISSIONS['platform:admin']),
  ADMIN: Object.values(PERMISSIONS).filter(
    (p) => !p.startsWith('billing:write') && p !== PERMISSIONS['platform:admin']
  ),
  MANAGER: [
    PERMISSIONS['business:read'],
    PERMISSIONS['team:read'],
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['knowledge:write'],
    PERMISSIONS['analytics:read'],
    PERMISSIONS['settings:read'],
    PERMISSIONS['audit:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['campaigns:write'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employees:write'],
    PERMISSIONS['employee-comms:read'],
    PERMISSIONS['employee-comms:write'],
  ],
  AGENT: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employee-comms:read'],
  ],
  RECEPTIONIST: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['customers:write'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['conversations:write'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['appointments:write'],
    PERMISSIONS['knowledge:read'],
    PERMISSIONS['analytics:read'],
    PERMISSIONS['campaigns:read'],
    PERMISSIONS['campaigns:write'],
    PERMISSIONS['employees:read'],
    PERMISSIONS['employee-comms:read'],
  ],
  STAFF: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['knowledge:read'],
  ],
  VIEWER: [
    PERMISSIONS['customers:read'],
    PERMISSIONS['conversations:read'],
    PERMISSIONS['appointments:read'],
    PERMISSIONS['analytics:read'],
  ],
};

export const SUBSCRIPTION_PLANS = {
  FREE: 'FREE',
  STARTER: 'STARTER',
  BUSINESS: 'BUSINESS',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE',
} as const;

export const INDUSTRIES = [
  'CLINIC',
  'HOSPITAL',
  'HOTEL',
  'RESTAURANT',
  'SALON',
  'UNIVERSITY',
  'TRAVEL_AGENCY',
  'REAL_ESTATE',
  'CONSULTING',
  'SERVICE_BUSINESS',
  'OTHER',
] as const;
